spring.application.name=ms-security
spring.mongodb.uri=mongodb+srv://kazeone:estiven10@cluster0.mvsrrsx.mongodb.net/?appName=Cluster0
spring.mongodb.database=db_security
server.port=8081
jwt.secret=fbc
jwt.expiration=3600000
